Step 1: Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Step2: Load Dataset

In [2]:
df = pd.read_csv('ai_job_market.csv')
df.head()

,job_id,company_name,industry,job_title,skills_required,experience_level,employment_type,location,salary_range_usd,posted_date,company_size,tools_preferred
0,1,Foster and Sons,Healthcare,Data Analyst,"NumPy, Reinforcement Learning, PyTorch, Scikit...",Mid,Full-time,"Tracybury, AR",92860-109598,2025-08-20,Large,"KDB+, LangChain"
1,2,"Boyd, Myers and Ramirez",Tech,Computer Vision Engineer,"Scikit-learn, CUDA, SQL, Pandas",Senior,Full-time,"Lake Scott, CU",78523-144875,2024-03-22,Large,"FastAPI, KDB+, TensorFlow"
2,3,King Inc,Tech,Quant Researcher,"MLflow, FastAPI, Azure, PyTorch, SQL, GCP",Entry,Full-time,"East Paige, CM",124496-217204,2025-09-18,Large,"BigQuery, PyTorch, Scikit-learn"
3,4,"Cooper, Archer and Lynch",Tech,AI Product Manager,"Scikit-learn, C++, Pandas, LangChain, AWS, R",Mid,Full-time,"Perezview, FI",50908-123743,2024-05-08,Large,"TensorFlow, BigQuery, MLflow"
4,5,Hall LLC,Finance,Data Scientist,"Excel, Keras, SQL, Hugging Face",Senior,Contract,"North Desireeland, NE",98694-135413,2025-02-24,Large,"PyTorch, LangChain"

In [6]:
df.head()

,job_id,company_name,industry,job_title,skills_required,experience_level,employment_type,location,salary_range_usd,posted_date,company_size,tools_preferred
0,1,Foster and Sons,Healthcare,Data Analyst,"NumPy, Reinforcement Learning, PyTorch, Scikit...",Mid,Full-time,"Tracybury, AR",92860-109598,2025-08-20,Large,"KDB+, LangChain"
1,2,"Boyd, Myers and Ramirez",Tech,Computer Vision Engineer,"Scikit-learn, CUDA, SQL, Pandas",Senior,Full-time,"Lake Scott, CU",78523-144875,2024-03-22,Large,"FastAPI, KDB+, TensorFlow"
2,3,King Inc,Tech,Quant Researcher,"MLflow, FastAPI, Azure, PyTorch, SQL, GCP",Entry,Full-time,"East Paige, CM",124496-217204,2025-09-18,Large,"BigQuery, PyTorch, Scikit-learn"
3,4,"Cooper, Archer and Lynch",Tech,AI Product Manager,"Scikit-learn, C++, Pandas, LangChain, AWS, R",Mid,Full-time,"Perezview, FI",50908-123743,2024-05-08,Large,"TensorFlow, BigQuery, MLflow"
4,5,Hall LLC,Finance,Data Scientist,"Excel, Keras, SQL, Hugging Face",Senior,Contract,"North Desireeland, NE",98694-135413,2025-02-24,Large,"PyTorch, LangChain"

In [7]:
df.shape

(2000, 12)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   job_id            2000 non-null   int64
 1   company_name      2000 non-null   object
 2   industry          2000 non-null   object
 3   job_title         2000 non-null   object
 4   skills_required   2000 non-null   object
 5   experience_level  2000 non-null   object
 6   employment_type   2000 non-null   object
 7   location          2000 non-null   object
 8   salary_range_usd  2000 non-null   object
 9   posted_date       2000 non-null   object
 10  company_size      2000 non-null   object
 11  tools_preferred   2000 non-null   object
dtypes: int64(1), object(11)
memory usage: 187.6+ KB

In [9]:
df.isnull().sum()

job_id              0
company_name        0
industry            0
job_title           0
skills_required     0
experience_level    0
employment_type     0
location            0
salary_range_usd    0
posted_date         0
company_size        0
tools_preferred     0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df['posted_date'] = pd.to_datetime(df['posted_date'])

In [13]:
df[['min_salary','max_salary']] = df['salary_range_usd'].str.split('-', expand=True)

In [14]:
df[['salary_range_usd','min_salary','max_salary']].head()

  salary_range_usd min_salary max_salary
0     92860-109598      92860     109598
1     78523-144875      78523     144875
2    124496-217204     124496     217204
3     50908-123743      50908     123743
4     98694-135413      98694     135413

In [15]:
df['min_salary'] = pd.to_numeric(df['min_salary'])
df['max_salary'] = pd.to_numeric(df['max_salary'])

In [16]:
df['avg_salary'] = (df['min_salary'] + df['max_salary']) / 2

In [17]:
df[['min_salary','max_salary','avg_salary']].head()

   min_salary  max_salary  avg_salary
0       92860      109598    101229.0
1       78523      144875    111699.0
2      124496      217204    170850.0
3       50908      123743     87325.5
4       98694      135413    117053.5

Basic Salary Analysis

In [18]:
df['avg_salary'].describe()

count      2000.000000
mean     123040.001500
std       34776.200983
min       47578.500000
25%       94466.250000
50%      123202.750000
75%      151413.000000
max      197776.500000
Name: avg_salary, dtype: float64

Highest-Paying Roles

In [19]:
df.groupby('job_title')['avg_salary'].mean().sort_values(ascending=False).head(10)

job_title
NLP Engineer                125307.552830
Data Analyst                125101.418819
ML Engineer                 123953.608000
Data Scientist              123449.302521
AI Researcher               123230.565401
Computer Vision Engineer    122881.143478
Quant Researcher            120505.292829
AI Product Manager          119715.292636
Name: avg_salary, dtype: float64

Count Job Roles

In [20]:
df['job_title'].value_counts().head(10)

job_title
Data Analyst                271
NLP Engineer                265
AI Product Manager          258
Quant Researcher            251
ML Engineer                 250
Data Scientist              238
AI Researcher               237
Computer Vision Engineer    230
Name: count, dtype: int64

**Analyze Experience Levels**

In [21]:
df['experience_level'].value_counts()

experience_level
Entry     702
Mid       668
Senior    630
Name: count, dtype: int64

**Salary by Experience**

In [22]:
df.groupby('experience_level')['avg_salary'].mean().sort_values(ascending=False)

experience_level
Senior    124329.096032
Entry     123404.258547
Mid       121441.441617
Name: avg_salary, dtype: float64

In [23]:
skills = []

for row in df['skills_required']:
    skills.extend(row.split(','))

skills = pd.Series([s.strip() for s in skills])

skills.value_counts().head(20)

TensorFlow                452
Excel                     432
Pandas                    427
FastAPI                   419
NumPy                     416
Reinforcement Learning    414
Azure                     413
SQL                       408
Hugging Face              408
Keras                     406
Power BI                  404
AWS                       404
GCP                       404
Python                    402
LangChain                 401
PyTorch                   401
Scikit-learn              400
Flask                     398
CUDA                      397
R                         393
Name: count, dtype: int64